const ICON_PATH = `/icons`;
const IMAGE_PATH = `/images`;
const LOGO_PATH = `/logos`;
const SVG_PATH = `/svgs`;
const CERTIFICATE_PATH = `/certificates`;
const SUPPORT_SERVICE = `/support_service`;
const SAFETY_CARD_INCOMPLETE_ICON = `/safety_card/incomplete_icon`;
const SAFETY_CARD = `/safety_card`;
const PRIZE_PATH = `/prize`;

export const assetPathProvider = {
  icon: {
    consultation: `${ICON_PATH}/consultation_icon.png`,
    selfDiagnosis: `${ICON_PATH}/self_diagnosis_icon.png`,
    selfDiagnosisWhite: `${ICON_PATH}/self_diagnosis_icon_white.png`,
    dangerControl: `${ICON_PATH}/danger_control_icon.png`,
    dangerInvestigation: `${ICON_PATH}/danger_investigation_icon.png`,
    download: `${ICON_PATH}/download_icon.png`,
    evaluation: `${ICON_PATH}/evaluation_icon.png`,
    leadership: `${ICON_PATH}/leadership_icon.png`,
    participation: `${ICON_PATH}/participation_icon.png`,
    plan: `${ICON_PATH}/plan_icon.png`,
    safe: `${ICON_PATH}/safe_icon.png`,
    instagram: `${ICON_PATH}/instagram_icon.png`,
    youtube: `${ICON_PATH}/youtube_icon.png`,
    rightArrow: `${ICON_PATH}/right_arrow_icon.png`,
    radioCheck: `${ICON_PATH}/radio_check_icon.png`,
    shieldCheck: `${ICON_PATH}/shield_check_icon.png`,
    user: `${ICON_PATH}/user_icon.png`,
    grayUser: `${ICON_PATH}/gray_user_icon.png`,
    personWithBuilding: `${ICON_PATH}/person_with_building_icon.png`,
    meeting: `${ICON_PATH}/meeting_icon.png`,
    tripleAngleBracket: `${ICON_PATH}/triple_angle_bracket.png`,
    signUp: `${ICON_PATH}/sign_up_icon.png`,
    starBadge: `${ICON_PATH}/star_badge_icon.png`,
    whiteCross: `${ICON_PATH}/white_cross_icon.png`,
    home: `${ICON_PATH}/home_icon.png`,
    doc: `${ICON_PATH}/doc_icon.png`,
    store: `${ICON_PATH}/store_icon.png`,
    lt: `${ICON_PATH}/lt_icon.png`,
    gt: `${ICON_PATH}/gt_icon.png`,
    refresh: `${ICON_PATH}/refresh_icon.png`,
    setting: `${ICON_PATH}/setting_icon.png`,
    threatDoc: `${ICON_PATH}/threat_doc_icon.png`,
    increase: `${ICON_PATH}/increase_icon.png`,
    officeBuilding: `${ICON_PATH}/office_building_icon.png`,
    dangerousZone: `${ICON_PATH}/dangerous_zone_icon.png`,
    helmetPerson: `${ICON_PATH}/person_with_helmet.png`,
    multipleFile: `${ICON_PATH}/multiple_file_icon.png`,
    activeStar: `${ICON_PATH}/active_star_icon.png`,
    inactiveStar: `${ICON_PATH}/inactive_star_icon.png`,
    close: `${ICON_PATH}/close_icon.png`,
    search: `${ICON_PATH}/search_icon.png`,
    chat: `${ICON_PATH}/chat_icon.png`,
    grayChat: `${ICON_PATH}/gray_chat_icon.png`,
    grayMultipleFile: `${ICON_PATH}/gray_multiple_file_icon.png`,
    desktopEmoji: `${ICON_PATH}/desktop_emoji_icon.png`,
    twoBubblesChat: `${ICON_PATH}/two_bubbles_chat_icon.png`,
    kakaoIcon: `${ICON_PATH}/kakaotalk_logo.png`,
    kakaoIcon2: `${ICON_PATH}/kakaotalk_sharing_btn_medium.png`,
    dropDownIcon: `${ICON_PATH}/drop_down_icon.png`,
    greenTriangleWarning: `${ICON_PATH}/green_triangle_warning.png`,
    emailIcon: `${ICON_PATH}/email_icon.png`,
    passwordIcon: `${ICON_PATH}/password_icon.png`,
    personWithPlus: `${ICON_PATH}/person_with_plus.png`,
    notice: `${ICON_PATH}/notice_icon.png`,
    news: `${ICON_PATH}/news_icon.png`,
    buddyChatIcon: `${ICON_PATH}/buddy_chat_icon.png`,
    circlePerson: `${ICON_PATH}/circle_person_icon.png`,
    dictionary: `${ICON_PATH}/dictionary_icon.png`,
    plusIcon: `${ICON_PATH}/plus_icon.png`,
    buildingIcon: `${ICON_PATH}/building_icon.png`,
    questionMarkIcon: `${ICON_PATH}/question_mark_icon.png`,
    informationIcon: `${ICON_PATH}/information_icon.png`,
    briefcaseIcon: `${ICON_PATH}/briefcase_icon.png`,
    pencilIcon: `${ICON_PATH}/pencil_icon.png`,
    safetyCardIcon: `${ICON_PATH}/safety_card_icon.png`,
    disabledSafetyCardIcon: `${ICON_PATH}/disabled_safety_card_icon.png`,
    buddyChatMenuIcon: `${ICON_PATH}/buddy_chat_menu_icon.png`,
    customerSupportIcon: `${ICON_PATH}/customer_support_icon.png`,
    filledSettingIcon: `${ICON_PATH}/filled_setting_icon.png`,
    whitePlusIcon: `${ICON_PATH}/white_plus_icon.png`,
    basicBadgeIcon: `${ICON_PATH}/basic_badge_icon.png`,
    graphIcon: `${ICON_PATH}/graph_icon.png`,
    groupMeetingIcon: `${ICON_PATH}/group_meeting_icon.png`,
    sosIcon: `${ICON_PATH}/sos_icon.png`,
    mintChatIcon: `${ICON_PATH}/mint_chat_icon.png`,
    megaphoneIcon: `${ICON_PATH}/megaphone_icon.png`,
    codeIcon: `${ICON_PATH}/code_icon.png`,
    mailIcon: `${ICON_PATH}/mail_icon.png`,
    facebookIcon: `${ICON_PATH}/facebook_icon.png`,
    uploadIcon: `${ICON_PATH}/upload_icon.png`,
    systemWhiteLeftSidebarDropdownIcon: `${ICON_PATH}/system_white_leftSidebar_dropdown_icon.png`,
    systemLeftSidebarDropdownIcon: `${ICON_PATH}/system_leftSidebar_dropdown_icon.png`,
    calendarIcon: `${ICON_PATH}/calendar_icon.png`,
    calendarColorIcon: `${ICON_PATH}/calendar_icon_color.png`,
    pinIcon: `${ICON_PATH}/pin_icon.png`,
    attachmentIcon: `${ICON_PATH}/attachment_icon.png`,
    linkIcon: `${ICON_PATH}/link_icon.png`,
    drawerIcon: `${ICON_PATH}/drawer_icon.png`,
    forwardPaperIcon: `${ICON_PATH}/forward_paper_icon.png`,
    pdfIcon: `${ICON_PATH}/pdf_icon.png`,
    menuBookIcon: `${ICON_PATH}/menu_book_icon.png`,
    userCheckIcon: `${ICON_PATH}/user_check_icon.png`,
    signDocIcon: `${ICON_PATH}/sign_doc_icon.png`,
    removeUserIcon: `${ICON_PATH}/remove_user_icon.png`,
    lockIcon: `${ICON_PATH}/lock_icon.png`,
    darkGrayPlusIcon: `${ICON_PATH}/dark_gray_plus_icon.png`,
    userAddIcon: `${ICON_PATH}/user_add_icon.png`,
    lineDownloadIcon: `${ICON_PATH}/line_download_icon.png`,
    logoutIcon: `${ICON_PATH}/logout_icon.png`,
    minusIcon: `${ICON_PATH}/minus_icon.png`,
    menuIcon: `${ICON_PATH}/menu_icon.png`,
    upLineIcon: `${ICON_PATH}/up_line_icon.png`,
    LineCheckIcon: `${ICON_PATH}/line_check_icon.png`,
    paymentCardIcon: `${ICON_PATH}/payment_card.png`,
    paymentTransIcon: `${ICON_PATH}/payment_trans.png`,
    paymentVbankIcon: `${ICON_PATH}/payment_vbank.png`,
    paymentKakaoIcon: `${ICON_PATH}/payment_kakao.png`,
    changeIcon: `${ICON_PATH}/change_icon.png`,
    printIcon: `${ICON_PATH}/print_icon.png`,
    binIcon: `${ICON_PATH}/bin_icon.png`,
    safeBuddyIcon: `${ICON_PATH}/safe_buddy_icon.png`,
    safetyCardRemoveIcon: `${ICON_PATH}/safety_card_remove_icon.png`,
    safetyCardAddIcon: `${ICON_PATH}/safety_card_add_icon.png`,
    safetyActivityReportIcon: `${ICON_PATH}/safety_activity_report_icon.png`,
    safetyInspectionIcon: `${ICON_PATH}/safety_inspection_icon.png`,
    announcementIcon: `${ICON_PATH}/announcement_icon.png`,
    issueMobileIcon: `${ICON_PATH}/issue_mobile_icon.png`,
    sosMobileIcon: `${ICON_PATH}/sos_mobile_icon.png`,
    safetyCardMobileIcon: `${ICON_PATH}/safety_card_mobile_icon.png`,
    budgetExecutionReportIcon: `${ICON_PATH}/budget_execution_report_icon.png`,
    riskAssessmentMobileIcon: `${ICON_PATH}/risk_assessment_mobile_icon.png`,
    trainingMobileIcon: `${ICON_PATH}/training_mobile_icon.png`,
    workerManagementIcon: `${ICON_PATH}/worker_management_icon.png`,
    studentIcon: `${ICON_PATH}/student_icon.png`,
    mobileBusinessPlusBadgeIcon: `${ICON_PATH}/mobile_business_plus_badge.png`,
    mobileBusinessPlusBadge: `${ICON_PATH}/mobile_business_plus_badge.png`,
    mobileProBadge: `${ICON_PATH}/mobile_pro_badge.png`,
    mobileBasicBadge: `${ICON_PATH}/mobile_basic_badge.png`,
    mobileFreeBadge: `${ICON_PATH}/mobile_free_badge.png`,
    whiteDropdownIcon: `${ICON_PATH}/white_dropdown_icon.png`,
    deleteIcon: `${ICON_PATH}/delete_icon.png`,
    threeStepIcon: `${ICON_PATH}/3_step_icon.png`,
    chartUpIcon: `${ICON_PATH}/chart-up-icon.png`,
    budgetIcon: `${ICON_PATH}/budget-icon.png`,

    // badges
    normalBadge: `${ICON_PATH}/normal_badge.png`,
    basicBadge: `${ICON_PATH}/basic_badge.png`,
    proBadge: `${ICON_PATH}/pro_badge.png`,
    enterpriseBadge: `${ICON_PATH}/enterprise_badge.png`,
    partnersBadge: `${ICON_PATH}/partners_badge.png`,

    //! deprecated, 삭제 예정
    pcBusinessPlusBadge: `${ICON_PATH}/pc_business_plus_badge.png`,
    pcProBadge: `${ICON_PATH}/pc_pro_badge.png`,
    pcBasicBadge: `${ICON_PATH}/pc_basic_badge.png`,
    pcFreeBadge: `${ICON_PATH}/pc_free_badge.png`,
  },
  image: {
    homeBackground: `${IMAGE_PATH}/home_background_image.png`,
    homeIphoneImage: `${IMAGE_PATH}/home_iphone_image.png`,
    companyBuilding: `${IMAGE_PATH}/company_building.png`,
    companyMountain: `${IMAGE_PATH}/company_mountain.png`,
    companyHistory: `${IMAGE_PATH}/company_history.png`,
    dummyCopyright: `${IMAGE_PATH}/company_dummy_copyright.png`,
    serviceBuilding: `${IMAGE_PATH}/service_building.png`,
    serviceBuilding2: `${IMAGE_PATH}/service_building_2.png`,
    serviceElectronicEquip: `${IMAGE_PATH}/service_electronic_equip.png`,
    serviceTyping: `${IMAGE_PATH}/service_typing.png`,
    serviceTypingBackground: `${IMAGE_PATH}/service_typing_bg.png`,
    chatBg: `${IMAGE_PATH}/chat_bg.png`,
    signUpIntroduction: `${IMAGE_PATH}/sign_up_introduction.png`,
    previewImage: `${IMAGE_PATH}/preview_image.png`,
    solutionIntroduction: `${IMAGE_PATH}/solution_introduction.png`,
    loginImage: `${IMAGE_PATH}/login_image.png`,
    companySolutionImage: `${IMAGE_PATH}/company_solution.png`,
    solutionGraphImage: `${IMAGE_PATH}/solution_graph_image.png`,
    businessLoginImage: `${IMAGE_PATH}/business_login_image.png`,
    taskManagementImage: `${IMAGE_PATH}/task_management_image.jpg`,
    taskCompleteImage: `${IMAGE_PATH}/task_complete_image.jpg`,
    safetyGoalImage: `${IMAGE_PATH}/safety_goal_image.png`,
    riskAssessmentHelp: `${IMAGE_PATH}/risk_assessment_help.png`,
    riskAssessmentFrequency: `${IMAGE_PATH}/risk_assessment_frequency.png`,
    plus43Image: `${IMAGE_PATH}/plus_4_3_image.png`,
    boardMan: `${IMAGE_PATH}/board-man.png`,
    chats: `${IMAGE_PATH}/chats.png`,
    seiimBot: `${IMAGE_PATH}/seiim-bot.png`,
    safebuddyMacbook: `${IMAGE_PATH}/sb-macbook.png`,
    serviceImage01: `${IMAGE_PATH}/service-image-01.png`,
    serviceMobileImage01: `${IMAGE_PATH}/service-mobile-img-01.png`,
    serviceMobileImage02: `${IMAGE_PATH}/service-mobile-img-02.png`,
    serviceMobileImage03: `${IMAGE_PATH}/service-mobile-img-03.png`,
    safeEdu: `${IMAGE_PATH}/company-safeedu-img.png`,
    safeMaster: `${IMAGE_PATH}/company-sm-img.png`,
    mainService: `${IMAGE_PATH}/service.png`,
    doc11: `${IMAGE_PATH}/doc_11.png`,
    aboutCompany: `${IMAGE_PATH}/about-company.png`,
  },
  logo: {
    seiim: `${LOGO_PATH}/seiim_logo.png`,
    saiifEdu: `${LOGO_PATH}/saiif_edu_logo.png`,
    safeMeister: `${LOGO_PATH}/safe_meister_logo.png`,
    eLinkForm: `${LOGO_PATH}/e_link_form_logo.png`,
    safeBuddy: `${LOGO_PATH}/safe_buddy_logo.png`,
    safeBuddy4x: `${LOGO_PATH}/safe_buddy_logo_4x.png`,
    safeBuddyWhite: `${LOGO_PATH}/safe_buddy_white_logo.png`,
    corebiz: `${LOGO_PATH}/corebiz_logo.png`,
    kosme: `${LOGO_PATH}/kosme_logo.png`,
    kscsa: `${LOGO_PATH}/kscsa_logo.png`,
    nationalLandSafety: `${LOGO_PATH}/national_land_safety_logo.png`,
    spf: `${LOGO_PATH}/spf_logo.png`,
    moel: `${LOGO_PATH}/moel_logo.png`,
    kosha: `${LOGO_PATH}/kosha_logo.png`,
    molit: `${LOGO_PATH}/molit_logo.png`,
    safebuddy: `${LOGO_PATH}/safebuddy_logo.png`,
    disaster: `${LOGO_PATH}/disaster_logo.png`,
    rsquare: `${LOGO_PATH}/rsquare_design_logo.png`,
    mobileMoel: `${LOGO_PATH}/mobile_moel_logo.png`,
    mobileKosha: `${LOGO_PATH}/mobile_kosha_logo.png`,
    mobileMolit: `${LOGO_PATH}/mobile_molit_logo.png`,
    mobileSafebuddy: `${LOGO_PATH}/mobile_safebuddy_logo.png`,
    mobileDisaster: `${LOGO_PATH}/mobile_disaster_logo.png`,
    koita: `${LOGO_PATH}/logo-koita.png`,
    molitWide: `${LOGO_PATH}/logo-molit.png`,
    jungso: `${LOGO_PATH}/logo-jungso.png`,
    kapa: `${LOGO_PATH}/logo-kapa.png`,
    findSafety: `${LOGO_PATH}/fine-safety.png`,
    icsm: `${LOGO_PATH}/icsm.png`,
    kalis: `${LOGO_PATH}/kalis.png`,
    kibo: `${LOGO_PATH}/kibo.png`,
    kosmeYoung: `${LOGO_PATH}/kosme-young.png`,
    sba: `${LOGO_PATH}/sba.png`,
    sccei: `${LOGO_PATH}/sccei.gif`,
    ventureEnterprise: `${LOGO_PATH}/venture-enterprise.png`,
    seiimV2: `${LOGO_PATH}/seiim-v2.png`,

    goodsoft: `${LOGO_PATH}/main1-goodsoft.png`,
    ve: `${LOGO_PATH}/main2-ve.png`,
    mainbiz: `${LOGO_PATH}/main3-mainbiz.png`,
    // koita: `${LOGO_PATH}/main4-koita.png`,
    start: `${LOGO_PATH}/main5-start.png`,

    customers: {
      hd: `${LOGO_PATH}/landing_customers/1-hd.png`,
      dl: `${LOGO_PATH}/landing_customers/2-dl.png`,
      shSng: `${LOGO_PATH}/landing_customers/3-sh-sng.png`,
      shScs: `${LOGO_PATH}/landing_customers/4-sh-scs.png`,
      ean: `${LOGO_PATH}/landing_customers/5-ean.png`,
      gau: `${LOGO_PATH}/landing_customers/6-gau.png`,
      ebm: `${LOGO_PATH}/landing_customers/7-ebm.png`,
      gaon: `${LOGO_PATH}/landing_customers/8-gaon.png`,
      baeksan: `${LOGO_PATH}/landing_customers/9-baeksan.png`,
      buyoung: `${LOGO_PATH}/landing_customers/10-buyoung.png`,
      sanha: `${LOGO_PATH}/landing_customers/11-sanha.png`,
      ocean: `${LOGO_PATH}/landing_customers/12-ocean.png`,
      carrier: `${LOGO_PATH}/landing_customers/13-carrier.png`,
      yk: `${LOGO_PATH}/landing_customers/14-yk.png`,
      insung: `${LOGO_PATH}/landing_customers/15-insung.png`,
      gtack: `${LOGO_PATH}/landing_customers/16-gtack.png`,
      hangyul: `${LOGO_PATH}/landing_customers/17-hangyul.png`,
      samjung: `${LOGO_PATH}/landing_customers/18-samjung.png`,
      heungwooConst: `${LOGO_PATH}/landing_customers/19-heungwoo-const.png`,
      heungwooInd: `${LOGO_PATH}/landing_customers/20-heungwoo-ind.png`,
      dowon: `${LOGO_PATH}/landing_customers/21-dowon.png`,
      shinyoung: `${LOGO_PATH}/landing_customers/22-shinyoung.png`,
      topwith: `${LOGO_PATH}/landing_customers/23-topwith.png`,
      hdasan: `${LOGO_PATH}/landing_customers/24-hdasan.png`,
      kihs: `${LOGO_PATH}/landing_customers/25-kihs.png`,
      hsuco: `${LOGO_PATH}/landing_customers/26-hsuco.png`,
      hoban: `${LOGO_PATH}/landing_customers/27-hoban.png`,
      spf: `${LOGO_PATH}/landing_customers/28-spf.png`,
      kapa: `${LOGO_PATH}/landing_customers/29-kapa.png`,
      kscsa: `${LOGO_PATH}/landing_customers/30-kscsa.png`,
      kalis: `${LOGO_PATH}/landing_customers/31-kalis.png`,
      hanwha: `${LOGO_PATH}/landing_customers/32-hanhwasolution.png`,
    },
  },
  svg: {
    announcement: `${SVG_PATH}/announcement_icon.svg`,
    file: `${SVG_PATH}/file_icon.svg`,
    fileUpload: `${SVG_PATH}/file_upload.svg`,
    kakao: `${SVG_PATH}/kakao.svg`,
    x: `${SVG_PATH}/x_icon.svg`,
    welcome: `${SVG_PATH}/welcome.svg`,
  },
  certificate: {
    business: `${CERTIFICATE_PATH}/business.png`,
    copyright: `${CERTIFICATE_PATH}/copyright.png`,
    production: `${CERTIFICATE_PATH}/production.png`,
    safePatent: `${CERTIFICATE_PATH}/safe_patent.png`,
    smartConstruction: `${CERTIFICATE_PATH}/smart_construction.png`,
    venturePrize: `${CERTIFICATE_PATH}/venture_prize.png`,
    venture: `${CERTIFICATE_PATH}/venture.png`,
    laboratory: `${CERTIFICATE_PATH}/laboratory.png`,
    new1: `${CERTIFICATE_PATH}/new1.png`,
    new2: `${CERTIFICATE_PATH}/new2.png`,
    new3: `${CERTIFICATE_PATH}/new3.png`,
    new4: `${CERTIFICATE_PATH}/new4.png`,
    new5: `${CERTIFICATE_PATH}/new5.png`,
    new6: `${CERTIFICATE_PATH}/new6.png`,
    new7: `${CERTIFICATE_PATH}/new7.png`,
    new8: `${CERTIFICATE_PATH}/new8.png`,
  },
  prize: {
    prize1: `${PRIZE_PATH}/prize1.png`,
    prize2: `${PRIZE_PATH}/prize2.png`,
    prize3: `${PRIZE_PATH}/prize3.png`,
    prize4: `${PRIZE_PATH}/prize4.png`,
    prize5: `${PRIZE_PATH}/prize5.png`,
  },
  supportService: {
    systemConsulting: `${SUPPORT_SERVICE}/01. 안전보건관리 체계구축 컨설팅 지원조건 확인.jpg`,
    riskConsulting: `${SUPPORT_SERVICE}/02. 위험성 평가 컨설팅 지원조건 확인.jpg`,
    cleanEnvironment: `${SUPPORT_SERVICE}/03. 클린사업장 조성지원 지원조건 확인.jpg`,
    loanSupport: `${SUPPORT_SERVICE}/04. 산업재해예방 융자지원 지원조건 확인.jpg`,
    partnerSupport: `${SUPPORT_SERVICE}/05. 안전동행지원 지원조건 확인.jpg`,
    ownerEducation: `${SUPPORT_SERVICE}/06. 안전보건관리 체계구축 사업주 교육 교육과정 확인.jpg`,
    managerEducation: `${SUPPORT_SERVICE}/07. 안전보건관리 체계구축 담당자 교육 교육과정 확인.jpg`,
  },
  safetyCard: {
    managementPolicy: `${SAFETY_CARD}/annual_report_business.png`,
    msdsTraining: `${SAFETY_CARD_INCOMPLETE_ICON}/msds_training.png`,
    newHireTraining: `${SAFETY_CARD_INCOMPLETE_ICON}/new_hire_training.png`,
    riskAssessmentAction: `${SAFETY_CARD_INCOMPLETE_ICON}/risk_assessment_action.png`,
    riskAssessment: `${SAFETY_CARD_INCOMPLETE_ICON}/risk_assessment.png`,
    safetyHealthBudget: `${SAFETY_CARD_INCOMPLETE_ICON}/safety_health_budget.png`,
    safetyHealthGoal: `${SAFETY_CARD_INCOMPLETE_ICON}/safety_health_goal.png`,
    safetyHealthInitiativeAndActionPlans: `${SAFETY_CARD_INCOMPLETE_ICON}/safety_health_initiative_and_action_plans.png`,
    safetyInspectionActions: `${SAFETY_CARD_INCOMPLETE_ICON}/safety_inspection_actions.png`,
    safetyInspections: `${SAFETY_CARD_INCOMPLETE_ICON}/safety_inspections.png`,
    specialSafetyHealthTraining: `${SAFETY_CARD_INCOMPLETE_ICON}/special_safety_health_training.png`,
    specialTypeWorkerTraining: `${SAFETY_CARD_INCOMPLETE_ICON}/special_type_worker_training.png`,
    supervisorsRegularTraining: `${SAFETY_CARD_INCOMPLETE_ICON}/supervisors_regular_training.png`,
    taskChangeTraining: `${SAFETY_CARD_INCOMPLETE_ICON}/task_change_training.png`,
    tbmTraining: `${SAFETY_CARD_INCOMPLETE_ICON}/tbm_training.png`,
    tbmPlusTraining: `${SAFETY_CARD_INCOMPLETE_ICON}/tbm_plus_training.png`,
    workersRegularTraining: `${SAFETY_CARD_INCOMPLETE_ICON}/workers_regular_training.png`,
    safetyHealthManagementPolicy: `${SAFETY_CARD_INCOMPLETE_ICON}/safety_health_management_policy.png`,
    tbmRiskAssessmentTraining: `${SAFETY_CARD_INCOMPLETE_ICON}/tbm_risk_assessment_training.png`,
  },
};
